 [profile.default]
   solc_version = "0.8.30"
   use_system_solc = true

optimizer = true
optimzer-runs = 200
out = "out"
src = "src"
test = "test"
libs = ["lib"]
remappings = [
  "some/other=lib/some-other/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

